name: MineStatus
version: 1.0.0
author: Maculos
main: com.maculos.minestatus.MineStatus
api-version: 1.14
commands:
  shutdown:
    description: Schedule a shutdown
    usage: /<command>
    aliases: sh